In [1]:
import numpy as np
import sys

In [2]:
a = np.array([[2,3,4,5], [6,7,8,9]])
b= np.array([[2,3,4,5], [6,7,8,9]])

In [3]:
result = np.add(a,b)
print(result)

[[ 4  6  8 10]
 [12 14 16 18]]


In [15]:
#array [row, column] achar a localizacao num array 2d, lebrar que comeca sempre pelo row or column 0
result[0,3]

10

In [17]:
result [0, :]

#o simbolo : vai retornar tudos os dados contidos na column

array([ 4,  6,  8, 10])